name: quant-env # 环境名称
channels:
  - defaults
  - conda-forge
dependencies:
  # 核心依赖
  - python=3.10
  - pandas>=2.0.0
  - numpy>=1.23.0
  - matplotlib>=3.7.0
  - pip>=23.0.0
  - pip:
      - yfinance>=0.2.18
      - alpha_vantage>=2.3.1
