name: quant-env  # 环境名称
channels:
  - defaults
  - conda-forge
dependencies:
  # 核心依赖
  - python=3.10
  - pandas>=2.0.0
  - numpy>=1.23.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - plotly>=5.15.0
  - seaborn>=0.12.0
  - jupyterlab>=3.6.0

  # 数据获取
  - yfinance>=0.2.18
  - alpha_vantage>=2.3.1
  - quandl>=3.7.0
  - ccxt>=4.0.0

  # 技术指标与回测
  - ta-lib>=0.4.24
  - vectorbt>=0.25.0
  - backtrader>=1.9.76.123
  - backtesting.py>=0.3.3
  - zipline>=2.0.0

  # 机器学习
  - scikit-learn>=1.2.0
  - tensorflow>=2.12.0
  - statsmodels>=0.14.0

  # 开发工具
  - black>=23.3.0
  - flake8>=6.0.0
  - pip>=23.0.0
  - pip:
      - loguru>=0.7.0
      - sentry-sdk>=1.25.0